/* This file has been generated by gen-symbols-attrs.py. */
/* Do not modify it or you'll get what you deserve */
// DO NOT MODIFY THIS FILE.
// It will be overwritten when gen-symbols-attrs.py or cxx-entity_specs.def are modified
#include "cxx-scope.h"
#include "cxx-nodecl-deep-copy.h"
#include "cxx-typeutils.h"
#include "string_utils.h"

    void symbol_deep_copy_entity_specs(scope_entry_t* dest, scope_entry_t* source,
             const decl_context_t* decl_context, symbol_map_t* symbol_map,
             nodecl_deep_copy_map_t* nodecl_deep_copy_map,
             symbol_deep_copy_map_t* symbol_deep_copy_map)
    {
    
symbol_entity_specs_set_is_static(dest, symbol_entity_specs_get_is_static(source));
symbol_entity_specs_set_is_register(dest, symbol_entity_specs_get_is_register(source));
symbol_entity_specs_set_is_extern(dest, symbol_entity_specs_get_is_extern(source));
symbol_entity_specs_set_is_thread(dest, symbol_entity_specs_get_is_thread(source));
symbol_entity_specs_set_is_thread_local(dest, symbol_entity_specs_get_is_thread_local(source));
symbol_entity_specs_set_is_mutable(dest, symbol_entity_specs_get_is_mutable(source));
symbol_entity_specs_set_is_export(dest, symbol_entity_specs_get_is_export(source));
symbol_entity_specs_set_is_inline(dest, symbol_entity_specs_get_is_inline(source));
symbol_entity_specs_set_is_virtual(dest, symbol_entity_specs_get_is_virtual(source));
symbol_entity_specs_set_is_pure(dest, symbol_entity_specs_get_is_pure(source));
symbol_entity_specs_set_is_builtin(dest, symbol_entity_specs_get_is_builtin(source));
symbol_entity_specs_set_is_deleted(dest, symbol_entity_specs_get_is_deleted(source));
symbol_entity_specs_set_is_defaulted(dest, symbol_entity_specs_get_is_defaulted(source));
symbol_entity_specs_set_is_conversion(dest, symbol_entity_specs_get_is_conversion(source));
symbol_entity_specs_set_is_trivial(dest, symbol_entity_specs_get_is_trivial(source));
symbol_entity_specs_set_is_constructor(dest, symbol_entity_specs_get_is_constructor(source));
symbol_entity_specs_set_is_default_constructor(dest, symbol_entity_specs_get_is_default_constructor(source));
symbol_entity_specs_set_is_copy_constructor(dest, symbol_entity_specs_get_is_copy_constructor(source));
symbol_entity_specs_set_is_move_constructor(dest, symbol_entity_specs_get_is_move_constructor(source));
symbol_entity_specs_set_is_conversor_constructor(dest, symbol_entity_specs_get_is_conversor_constructor(source));
symbol_entity_specs_set_is_copy_assignment_operator(dest, symbol_entity_specs_get_is_copy_assignment_operator(source));
symbol_entity_specs_set_is_move_assignment_operator(dest, symbol_entity_specs_get_is_move_assignment_operator(source));
symbol_entity_specs_set_is_destructor(dest, symbol_entity_specs_get_is_destructor(source));
symbol_entity_specs_set_is_explicit(dest, symbol_entity_specs_get_is_explicit(source));
symbol_entity_specs_set_is_surrogate_function(dest, symbol_entity_specs_get_is_surrogate_function(source));
symbol_entity_specs_set_is_anonymous_union(dest, symbol_entity_specs_get_is_anonymous_union(source));
symbol_entity_specs_set_is_member_of_anonymous(dest, symbol_entity_specs_get_is_member_of_anonymous(source));
symbol_entity_specs_set_is_user_declared(dest, symbol_entity_specs_get_is_user_declared(source));
symbol_entity_specs_set_is_instantiable(dest, symbol_entity_specs_get_is_instantiable(source));
symbol_entity_specs_set_is_instantiated(dest, symbol_entity_specs_get_is_instantiated(source));
symbol_entity_specs_set_is_template_parameter(dest, symbol_entity_specs_get_is_template_parameter(source));
symbol_entity_specs_set_is_member(dest, symbol_entity_specs_get_is_member(source));
symbol_entity_specs_set_is_bitfield(dest, symbol_entity_specs_get_is_bitfield(source));
symbol_entity_specs_set_is_unnamed_bitfield(dest, symbol_entity_specs_get_is_unnamed_bitfield(source));
symbol_entity_specs_set_is_friend_declared(dest, symbol_entity_specs_get_is_friend_declared(source));
symbol_entity_specs_set_any_exception(dest, symbol_entity_specs_get_any_exception(source));
symbol_entity_specs_set_is_injected_class_name(dest, symbol_entity_specs_get_is_injected_class_name(source));
symbol_entity_specs_set_is_unnamed(dest, symbol_entity_specs_get_is_unnamed(source));
symbol_entity_specs_set_is_defined_inside_class_specifier(dest, symbol_entity_specs_get_is_defined_inside_class_specifier(source));
symbol_entity_specs_set_is_nested_function(dest, symbol_entity_specs_get_is_nested_function(source));
symbol_entity_specs_set_is_saved_expression(dest, symbol_entity_specs_get_is_saved_expression(source));
symbol_entity_specs_set_gcc_extension(dest, symbol_entity_specs_get_gcc_extension(source));
symbol_entity_specs_set_is_result_var(dest, symbol_entity_specs_get_is_result_var(source));
symbol_entity_specs_set_is_constexpr(dest, symbol_entity_specs_get_is_constexpr(source));
symbol_entity_specs_set_is_override(dest, symbol_entity_specs_get_is_override(source));
symbol_entity_specs_set_is_final(dest, symbol_entity_specs_get_is_final(source));
symbol_entity_specs_set_is_hides_member(dest, symbol_entity_specs_get_is_hides_member(source));
symbol_entity_specs_set_is_global_hidden(dest, symbol_entity_specs_get_is_global_hidden(source));
symbol_entity_specs_set_is_implicit_basic_type(dest, symbol_entity_specs_get_is_implicit_basic_type(source));
symbol_entity_specs_set_is_allocatable(dest, symbol_entity_specs_get_is_allocatable(source));
symbol_entity_specs_set_is_in_common(dest, symbol_entity_specs_get_is_in_common(source));
symbol_entity_specs_set_is_in_namelist(dest, symbol_entity_specs_get_is_in_namelist(source));
symbol_entity_specs_set_is_optional(dest, symbol_entity_specs_get_is_optional(source));
symbol_entity_specs_set_is_target(dest, symbol_entity_specs_get_is_target(source));
symbol_entity_specs_set_is_elemental(dest, symbol_entity_specs_get_is_elemental(source));
symbol_entity_specs_set_is_recursive(dest, symbol_entity_specs_get_is_recursive(source));
symbol_entity_specs_set_is_stmt_function(dest, symbol_entity_specs_get_is_stmt_function(source));
symbol_entity_specs_set_is_intrinsic_subroutine(dest, symbol_entity_specs_get_is_intrinsic_subroutine(source));
symbol_entity_specs_set_is_intrinsic_function(dest, symbol_entity_specs_get_is_intrinsic_function(source));
symbol_entity_specs_set_is_module_procedure(dest, symbol_entity_specs_get_is_module_procedure(source));
symbol_entity_specs_set_is_entry(dest, symbol_entity_specs_get_is_entry(source));
symbol_entity_specs_set_is_renamed(dest, symbol_entity_specs_get_is_renamed(source));
symbol_entity_specs_set_is_cray_pointee(dest, symbol_entity_specs_get_is_cray_pointee(source));
symbol_entity_specs_set_is_cray_pointer(dest, symbol_entity_specs_get_is_cray_pointer(source));
symbol_entity_specs_set_is_saved_program_unit(dest, symbol_entity_specs_get_is_saved_program_unit(source));
symbol_entity_specs_set_is_contiguous(dest, symbol_entity_specs_get_is_contiguous(source));
symbol_entity_specs_set_is_procedure_decl_stmt(dest, symbol_entity_specs_get_is_procedure_decl_stmt(source));
symbol_entity_specs_set_is_abstract(dest, symbol_entity_specs_get_is_abstract(source));
symbol_entity_specs_set_result_var(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_result_var(source)));
symbol_entity_specs_set_alias_to(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_alias_to(source)));
symbol_entity_specs_set_emission_template(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_emission_template(source)));
symbol_entity_specs_set_anonymous_accessor(dest, nodecl_deep_copy_compute_maps(symbol_entity_specs_get_anonymous_accessor(source), decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map));
symbol_entity_specs_set_intent_kind(dest, symbol_entity_specs_get_intent_kind(source));
symbol_entity_specs_set_in_common(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_in_common(source)));
symbol_entity_specs_set_namelist(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_namelist(source)));
{
symbol_entity_specs_free_related_symbols(dest);
int i, N = symbol_entity_specs_get_num_related_symbols(source);
for (i = 0; i < N; i++)
{
scope_entry_t* copied = symbol_map->map(symbol_map, symbol_entity_specs_get_related_symbols_num(source, i));
symbol_entity_specs_add_related_symbols(dest, copied);
}
}
{
symbol_entity_specs_free_friend_candidates(dest);
int i, N = symbol_entity_specs_get_num_friend_candidates(source);
for (i = 0; i < N; i++)
{
scope_entry_t* copied = symbol_map->map(symbol_map, symbol_entity_specs_get_friend_candidates_num(source, i));
symbol_entity_specs_add_friend_candidates(dest, copied);
}
}
symbol_entity_specs_set_specific_intrinsic(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_specific_intrinsic(source)));
symbol_entity_specs_set_access(dest, symbol_entity_specs_get_access(source));
symbol_entity_specs_set_template_parameter_nesting(dest, symbol_entity_specs_get_template_parameter_nesting(source));
symbol_entity_specs_set_template_parameter_position(dest, symbol_entity_specs_get_template_parameter_position(source));
symbol_entity_specs_set_class_type(dest, type_deep_copy_compute_maps(symbol_entity_specs_get_class_type(source), /* symbol dest */ NULL, decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map));
symbol_entity_specs_set_from_module(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_from_module(source)));
symbol_entity_specs_set_from_module_name(dest, symbol_entity_specs_get_from_module_name(source));
symbol_entity_specs_set_in_module(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_in_module(source)));
symbol_entity_specs_set_cray_pointer(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_cray_pointer(source)));
symbol_entity_specs_set_used_modules(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_used_modules(source)));
symbol_entity_specs_set_procedure_decl_stmt_proc_interface(dest, symbol_map->map(symbol_map, symbol_entity_specs_get_procedure_decl_stmt_proc_interface(source)));
symbol_entity_specs_set_linkage_spec(dest, symbol_entity_specs_get_linkage_spec(source));
symbol_entity_specs_set_noexception(dest, nodecl_deep_copy_compute_maps(symbol_entity_specs_get_noexception(source), decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map));
{
symbol_entity_specs_free_exceptions(dest);
int i, N = symbol_entity_specs_get_num_exceptions(source);
for (i = 0; i < N; i++)
{
type_t* copied = type_deep_copy_compute_maps(symbol_entity_specs_get_exceptions_num(source, i), /* dest */ NULL, decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map);
symbol_entity_specs_add_exceptions(dest, copied);
}
}
{
symbol_entity_specs_free_function_parameter_info(dest);
int i, N = symbol_entity_specs_get_num_function_parameter_info(source);
for (i = 0; i < N; i++)
{
function_parameter_info_t param_info = symbol_entity_specs_get_function_parameter_info_num(source, i);
param_info.function = symbol_map->map(symbol_map, param_info.function);
symbol_entity_specs_add_function_parameter_info(dest, param_info);
}
}
{
symbol_entity_specs_free_default_argument_info(dest);
int i, N = symbol_entity_specs_get_num_parameters(source);
for (i = 0; i < N; i++)
{
default_argument_info_t* source_default_arg = symbol_entity_specs_get_default_argument_info_num(source, i);
default_argument_info_t* copied = NULL;
if (source_default_arg != NULL)
{
  copied = NEW0(default_argument_info_t);
  copied->argument = nodecl_deep_copy_compute_maps(source_default_arg->argument, decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map);
  copied->context = decl_context;
}
symbol_entity_specs_add_default_argument_info(dest, copied);
}
}
symbol_entity_specs_set_bitfield_size(dest, nodecl_deep_copy_compute_maps(symbol_entity_specs_get_bitfield_size(source), decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map));
symbol_entity_specs_set_bitfield_offset(dest, symbol_entity_specs_get_bitfield_offset(source));
symbol_entity_specs_set_bitfield_first(dest, symbol_entity_specs_get_bitfield_first(source));
symbol_entity_specs_set_bitfield_last(dest, symbol_entity_specs_get_bitfield_last(source));
symbol_entity_specs_set_field_offset(dest, symbol_entity_specs_get_field_offset(source));
{
symbol_entity_specs_free_gcc_attributes(dest);
int i, N = symbol_entity_specs_get_num_gcc_attributes(source);
for (i = 0; i < N; i++)
{
gcc_attribute_t source_gcc_attr = symbol_entity_specs_get_gcc_attributes_num(source, i);
gcc_attribute_t copied;
copied.attribute_name = source_gcc_attr.attribute_name;
copied.expression_list = nodecl_deep_copy_compute_maps(source_gcc_attr.expression_list, decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map);
symbol_entity_specs_add_gcc_attributes(dest, copied);
}
}
{
symbol_entity_specs_free_ms_attributes(dest);
int i, N = symbol_entity_specs_get_num_ms_attributes(source);
for (i = 0; i < N; i++)
{
gcc_attribute_t source_gcc_attr = symbol_entity_specs_get_ms_attributes_num(source, i);
gcc_attribute_t copied;
copied.attribute_name = source_gcc_attr.attribute_name;
copied.expression_list = nodecl_deep_copy_compute_maps(source_gcc_attr.expression_list, decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map);
symbol_entity_specs_add_ms_attributes(dest, copied);
}
}
symbol_entity_specs_set_simplify_function(dest, symbol_entity_specs_get_simplify_function(source));
symbol_entity_specs_set_bind_info(dest, nodecl_deep_copy_compute_maps(symbol_entity_specs_get_bind_info(source), decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map));
symbol_entity_specs_set_asm_specification(dest, nodecl_deep_copy_compute_maps(symbol_entity_specs_get_asm_specification(source), decl_context, symbol_map, nodecl_deep_copy_map, symbol_deep_copy_map));

    }
    
