#!/usr/bin/env bash


# Restrict these tests to AMD64
if [ $(uname -m) = x86_64 ];
then
    /home/jenkins-runner/workspace/OmpSs/ompss-xx.yy-1-start/mcxx/tests/config/mercurium
else
    echo "test_ignore=yes"
    echo "test_ignore_reason=\"Only run in x86_64\""
fi
